name: certora

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

    workflow_dispatch:

jobs:
    verify:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                rule: ["verifyOwners.sh", "verifySafe.sh", "verifyModules.sh", "verifyNativeTokenRefund.sh"]

        steps:
            - uses: actions/checkout@v3

            - name: Install python
              uses: actions/setup-python@v4
              with: { python-version: 3.11 }

            - name: Install java
              uses: actions/setup-java@v3
              with: { java-version: "17", java-package: jre, distribution: semeru }

            - name: Install certora cli
              run: pip install -Iv certora-cli

            - name: Install solc
              run: |
                  wget https://github.com/ethereum/solidity/releases/download/v0.7.6/solc-static-linux
                  chmod +x solc-static-linux
                  sudo mv solc-static-linux /usr/local/bin/solc7.6

                  wget https://github.com/ethereum/solidity/releases/download/v0.8.19/solc-static-linux
                  chmod +x solc-static-linux
                  sudo mv solc-static-linux /usr/local/bin/solc8.19

            - name: Verify rule ${{ matrix.rule }}
              run: |
                  cd certora
                  touch applyHarness.patch
                  make munged
                  cd ..
                  echo "key length" ${#CERTORAKEY}
                  ./certora/scripts/${{ matrix.rule }}
              env:
                  CERTORAKEY: ${{ secrets.CERTORA_KEY }}
