name: safe-smart-account
on: [push, pull_request]
env:
    NODE_VERSION: 18.17.1

jobs:
    lint-solidity:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
            - run: npm ci
            - run: npm run lint:sol:prettier
            - run: npm run lint:sol

    lint-typescript:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
            - run: npm ci
            - run: npm run lint:ts:prettier
            - run: npm run lint:ts

    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                contract-name: ["Safe", "SafeL2"]
        env:
            SAFE_CONTRACT_UNDER_TEST: ${{ matrix.contract-name }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
            - run: npm ci
            - run: npm run build
            - run: npm run coverage
            - name: Send coverage to Coveralls (parallel)
              uses: coverallsapp/github-action@v2
              with:
                  parallel: true
                  flag-name: run-$
                  github-token: ${{ secrets.GITHUB_TOKEN }}

    finish:
        runs-on: ubuntu-latest
        needs: tests
        if: ${{ always() }}
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@v2
              with:
                  parallel-finished: true
                  carryforward: "run-Safe,run-SafeL2"

    benchmarks:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                solidity: ["0.7.6", "0.8.24"]
                include:
                    - solidity: "0.8.24"
                      settings: '{"viaIR":true,"optimizer":{"enabled":true,"runs":1000000}}'
        env:
            SOLIDITY_VERSION: ${{ matrix.solidity }}
            SOLIDITY_SETTINGS: ${{ matrix.settings }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: "npm"
            - run: npm ci && npm run build && npx hardhat codesize --contractname Safe && npm run benchmark
