name: safe-contracts
on: [push, pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.17.1
                  cache: 'npm'
            - run: npm ci 
            - run: npm run build
            - run: npm run coverage
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.17.1
                  cache: 'npm'
            - run: npm ci
            - run: npm run lint:sol && npm run lint:ts && npm run lint:sol:prettier
    tests-other:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                contract-name: ["SafeL2"]
        env:
            SAFE_CONTRACT_UNDER_TEST: ${{ matrix.contract-name }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.17.1
                  cache: 'npm'
            - run: npm ci 
            - run: npm run build
            - run: npm run coverage
            - name: Coveralls
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
    benchmarks:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                solidity: ["0.7.6", "0.8.19"]
                include:
                    - solidity: "0.8.19"
                      settings: '{"viaIR":true,"optimizer":{"enabled":true,"runs":1000000}}'
        env:
            SOLIDITY_VERSION: ${{ matrix.solidity }}
            SOLIDITY_SETTINGS: ${{ matrix.settings }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 18.17.1
                  cache: 'npm'
            - run: (npm ci && npm run build && npx hardhat codesize --contractname Safe && npm run benchmark) || echo "Benchmark failed"
